name: lol
description: LoL Profile.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 3.0.0

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+2
  provider: ^2.0.1
  shared_preferences: ^0.5.2
  flutter_circular_chart: ^0.1.0
  charts_flutter: ^0.6.0
  dynamic_theme: ^1.0.1
  flutter_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/champs/champs.json
    - assets/images/lol-profile.png
    - assets/images/background.jpg
    - assets/images/level-5.png
    - assets/images/level-4.png
    - assets/images/level-3.png
    - assets/images/level-2.png
    - assets/images/unknown.png
    - assets/champs/images/Aatrox.png
    - assets/champs/images/Ahri.png
    - assets/champs/images/Akali.png
    - assets/champs/images/Alistar.png
    - assets/champs/images/Amumu.png
    - assets/champs/images/Anivia.png
    - assets/champs/images/Annie.png
    - assets/champs/images/Ashe.png
    - assets/champs/images/AurelionSol.png
    - assets/champs/images/Azir.png
    - assets/champs/images/Bard.png
    - assets/champs/images/Blitzcrank.png
    - assets/champs/images/Brand.png
    - assets/champs/images/Braum.png
    - assets/champs/images/Caitlyn.png
    - assets/champs/images/Camille.png
    - assets/champs/images/Cassiopeia.png
    - assets/champs/images/Chogath.png
    - assets/champs/images/Corki.png
    - assets/champs/images/Darius.png
    - assets/champs/images/Diana.png
    - assets/champs/images/Draven.png
    - assets/champs/images/DrMundo.png
    - assets/champs/images/Ekko.png
    - assets/champs/images/Elise.png
    - assets/champs/images/Evelynn.png
    - assets/champs/images/Ezreal.png
    - assets/champs/images/Fiddlesticks.png
    - assets/champs/images/Fiora.png
    - assets/champs/images/Fizz.png
    - assets/champs/images/Galio.png
    - assets/champs/images/Gangplank.png
    - assets/champs/images/Garen.png
    - assets/champs/images/Gnar.png
    - assets/champs/images/Gragas.png
    - assets/champs/images/Graves.png
    - assets/champs/images/Hecarim.png
    - assets/champs/images/Heimerdinger.png
    - assets/champs/images/Illaoi.png
    - assets/champs/images/Irelia.png
    - assets/champs/images/Ivern.png
    - assets/champs/images/Janna.png
    - assets/champs/images/JarvanIV.png
    - assets/champs/images/Jax.png
    - assets/champs/images/Jayce.png
    - assets/champs/images/Jhin.png
    - assets/champs/images/Jinx.png
    - assets/champs/images/Kaisa.png
    - assets/champs/images/Kalista.png
    - assets/champs/images/Karma.png
    - assets/champs/images/Karthus.png
    - assets/champs/images/Kassadin.png
    - assets/champs/images/Katarina.png
    - assets/champs/images/Kayle.png
    - assets/champs/images/Kayn.png
    - assets/champs/images/Kennen.png
    - assets/champs/images/Khazix.png
    - assets/champs/images/Kindred.png
    - assets/champs/images/Kled.png
    - assets/champs/images/KogMaw.png
    - assets/champs/images/Leblanc.png
    - assets/champs/images/LeeSin.png
    - assets/champs/images/Leona.png
    - assets/champs/images/Lissandra.png
    - assets/champs/images/Lucian.png
    - assets/champs/images/Lulu.png
    - assets/champs/images/Lux.png
    - assets/champs/images/Malphite.png
    - assets/champs/images/Malzahar.png
    - assets/champs/images/Maokai.png
    - assets/champs/images/MasterYi.png
    - assets/champs/images/MissFortune.png
    - assets/champs/images/MonkeyKing.png
    - assets/champs/images/Mordekaiser.png
    - assets/champs/images/Morgana.png
    - assets/champs/images/Nami.png
    - assets/champs/images/Nasus.png
    - assets/champs/images/Nautilus.png
    - assets/champs/images/Neeko.png
    - assets/champs/images/Nidalee.png
    - assets/champs/images/Nocturne.png
    - assets/champs/images/Nunu.png
    - assets/champs/images/Olaf.png
    - assets/champs/images/Orianna.png
    - assets/champs/images/Ornn.png
    - assets/champs/images/Pantheon.png
    - assets/champs/images/Poppy.png
    - assets/champs/images/Pyke.png
    - assets/champs/images/Qiyana.png
    - assets/champs/images/Quinn.png
    - assets/champs/images/Rakan.png
    - assets/champs/images/Rammus.png
    - assets/champs/images/RekSai.png
    - assets/champs/images/Renekton.png
    - assets/champs/images/Rengar.png
    - assets/champs/images/Riven.png
    - assets/champs/images/Rumble.png
    - assets/champs/images/Ryze.png
    - assets/champs/images/Sejuani.png
    - assets/champs/images/Shaco.png
    - assets/champs/images/Shen.png
    - assets/champs/images/Shyvana.png
    - assets/champs/images/Singed.png
    - assets/champs/images/Sion.png
    - assets/champs/images/Sivir.png
    - assets/champs/images/Skarner.png
    - assets/champs/images/Sona.png
    - assets/champs/images/Soraka.png
    - assets/champs/images/Swain.png
    - assets/champs/images/Sylas.png
    - assets/champs/images/Syndra.png
    - assets/champs/images/TahmKench.png
    - assets/champs/images/Taliyah.png
    - assets/champs/images/Talon.png
    - assets/champs/images/Taric.png
    - assets/champs/images/Teemo.png
    - assets/champs/images/Thresh.png
    - assets/champs/images/Tristana.png
    - assets/champs/images/Trundle.png
    - assets/champs/images/Tryndamere.png
    - assets/champs/images/TwistedFate.png
    - assets/champs/images/Twitch.png
    - assets/champs/images/Udyr.png
    - assets/champs/images/unknown.png
    - assets/champs/images/Urgot.png
    - assets/champs/images/Varus.png
    - assets/champs/images/Vayne.png
    - assets/champs/images/Veigar.png
    - assets/champs/images/Velkoz.png
    - assets/champs/images/Vi.png
    - assets/champs/images/Viktor.png
    - assets/champs/images/Vladimir.png
    - assets/champs/images/Volibear.png
    - assets/champs/images/Warwick.png
    - assets/champs/images/Xayah.png
    - assets/champs/images/Xerath.png
    - assets/champs/images/XinZhao.png
    - assets/champs/images/Yasuo.png
    - assets/champs/images/Yorick.png
    - assets/champs/images/Yuumi.png
    - assets/champs/images/Zac.png
    - assets/champs/images/Zed.png
    - assets/champs/images/Ziggs.png
    - assets/champs/images/Zilean.png
    - assets/champs/images/Zoe.png
    - assets/champs/images/Zyra.png

  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
